---
- name: Container and server deployment
  hosts: all
  become: true

  vars:
    repo_dest: /opt/product-service
    repo_url: https://github.com/nbicocchi/product-service-ci-cd.git

  tasks:
    - name: Ensure Git is installed
      apt:
        name: git
        state: present
        update_cache: yes

    - name: Clone or update repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dest }}"
        version: main
        force: yes

    - name: Ensure Docker service is running
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Stop all running containers
      shell: docker ps -q | xargs -r docker stop
      register: stop_result
      changed_when: stop_result.stdout != ""

    - name: Remove stopped containers (optional cleanup)
      shell: docker container prune -f
      when: stop_result.stdout != ""

    - name: Restart containers
      command: docker compose up -d
      args:
        chdir: "{{ repo_dest }}"
