---
- name: Container and server starting
  hosts: all
  become: true

  vars:
    repo_dest: /opt/product-service

  tasks:
    - name: Check git installation
      apt:
        name: git
        state: present
        update_cache: yes

    - name: Clone or update repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dest }}"
        version: main
        force: yes

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Start container
      command: docker compose up -d
      args:
        chdir: "{{ repo_dest }}"