name: Infrastructure provisioning

on:
  workflow_dispatch:

jobs:
  infrastructure:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    environment:
      name: Infrastructure provisioning

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.3

      - name: Terraform init
        id: init
        run: terraform init -input=false
        working-directory: terraform

      - name: Terraform plan
        id: plan
        run: terraform plan -input=false -var-file=terraform.tfvars
        working-directory: terraform

      - name: Terraform apply
        id: apply
        run: terraform apply -input=false -auto-approve -var-file=terraform.tfvars
        working-directory: terraform

      - name: Get OpenSSH private key
        id: get_key
        run: |
          PRIVATE_KEY=$(terraform output -raw private_key_openssh)
          echo "$PRIVATE_KEY"
        working-directory: terraform